[package]
name = "rascii"
version = "0.1.0"
authors = ["jacobmiller22 <jacobmiller22@vt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
